set_property IOSTANDARD LVCMOS33 [get_ports {logic_in[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {logic_in[0]}]

set_property PACKAGE_PIN U2 [get_ports {logic_in[1]}]
set_property PACKAGE_PIN V2 [get_ports {logic_in[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports cs]
set_property IOSTANDARD LVCMOS33 [get_ports dc]
set_property IOSTANDARD LVCMOS33 [get_ports mosi]
set_property IOSTANDARD LVCMOS33 [get_ports pmoden]
set_property IOSTANDARD LVCMOS33 [get_ports res_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports sclk]
set_property IOSTANDARD LVCMOS33 [get_ports vccen]
set_property PACKAGE_PIN F14 [get_ports clk]
set_property PACKAGE_PIN R4 [get_ports cs]
set_property PACKAGE_PIN L5 [get_ports dc]
set_property PACKAGE_PIN T3 [get_ports mosi]
set_property PACKAGE_PIN L4 [get_ports pmoden]
set_property PACKAGE_PIN M4 [get_ports res_n]
set_property PACKAGE_PIN J1 [get_ports rst]
set_property PACKAGE_PIN N4 [get_ports sclk]
set_property PACKAGE_PIN K4 [get_ports vccen]

set_property DRIVE 12 [get_ports sclk]


set_property PACKAGE_PIN J2 [get_ports speed_switch]
set_property IOSTANDARD LVCMOS33 [get_ports speed_switch]

set_property PACKAGE_PIN U1 [get_ports {logic_in[2]}]
set_property PACKAGE_PIN T2 [get_ports {logic_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {logic_in[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {logic_in[2]}]

set_property IOSTANDARD LVCMOS33 [get_ports {logic_in_external[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {logic_in_external[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {logic_in_external[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {logic_in_external[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports freeze_button]
set_property IOSTANDARD LVCMOS33 [get_ports mode_select]
set_property PACKAGE_PIN V2 [get_ports {logic_in_external[3]}]
set_property PACKAGE_PIN U2 [get_ports {logic_in_external[2]}]
set_property PACKAGE_PIN U1 [get_ports {logic_in_external[1]}]
set_property PACKAGE_PIN T2 [get_ports {logic_in_external[0]}]
set_property PACKAGE_PIN T1 [get_ports mode_select]
set_property PACKAGE_PIN R2 [get_ports freeze_button]
